AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 150
    MemorySize: 400

Resources:
  LambdaFunctionOverHttps:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /predict
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.9-v1

Outputs:
  InferenceApi:
    Description: "API Gateway endpoint URL for Prod stage for Inference function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  LambdaFunctionOverHttps:
    Description: "Inference Lambda Function ARN"
    Value: !GetAtt LambdaFunctionOverHttps.Arn
  LambdaFunctionOverHttpsIamRole:
    Description: "Implicit IAM Role created for Inference function"
    Value: !GetAtt LambdaFunctionOverHttps.Arn
